### ISSUE TITLE
Dataset download connection error.

### ISSUE THREAD

**Issue by YangJae96** [anDoer/PoseTrack21#9]
Hello, I was trying to download the dataset with the token, but below error message occurs. 

```
python3 download_dataset.py --save_path /root/workplace/dataset --token [my token]
[1] 27333

bash:: No such file or directory
root@33be3af70b75:~/workplace/person_search/PoseTrack21# [0 / 18]Downloading https://posetrack.net/posetrack18-data//posetrack18_images.tar.aa
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: 
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8055c4a358>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:
```

I think the website is blocking me, could I get some help?

Thanks in advance.

**Comment by anDoer** [comment]
Please try to put the token into quotation marks. This should resolve the issue.

```
python3 download_dataset.py --save_path /root/workplace/dataset --token="[my token]" --video_source_url="[new url we provided]"
```

Addtionally, as stated [in this document](https://github.com/anDoer/PoseTrack21/blob/main/doc/how_to_download.md), please add the alternative download link we provided to you by e-mail.

**Comment by YangJae96** [comment]
@anDoer Thanks. I solved the issue!
